<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-09-08T15:39:51-04:00" hostname="https://newco--dev.my.salesforce.com" tests="1" failures="1"  errors="0"  time="18.15">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Sep 8, 2020 3:39 PM"/>
            <property name="testExecutionTime" value="18.15 s"/>
            <property name="testTotalTime" value="18.15 s"/>
            <property name="commandTime" value="26.58 s"/>
            <property name="hostname" value="https://newco--dev.my.salesforce.com"/>
            <property name="orgId" value="00D5C0000008qu6UAA"/>
            <property name="username" value="mark.moser@dllgroup.com.dev"/>
            <property name="testRunId" value="7075C00000hEq4y"/>
            <property name="userId" value="0051I000000cQh5QAE"/>
        </properties>
        <testcase name="testVertexOnCharge" classname="TestGetTaxonChargesJob" time="18.15">
            <failure message="System.DmlException: Update failed. First exception on row 0; first error: MISSING_ARGUMENT, Id not specified in an update call: []"><![CDATA[Class.TestGetTaxonChargesJob.testVertexOnCharge: line 46, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
